# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'BProtective' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BProtective
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'MaterialComponents'

end
